/* eslint-disable */

type __WebviewWindow__ =
  | import("@tauri-apps/api/webview").Webview
  | import("@tauri-apps/api/window").Window;

type __EventObj__<T> = {
  listen: (cb: (event: { payload: T }) => void) => Promise<() => void>;
  once: (cb: (event: { payload: T }) => void) => Promise<() => void>;
  emit: T extends null ? () => Promise<void> : (payload: T) => Promise<void>;
};

export type EventsShape<T extends Record<string, any>> = {
  [K in keyof T]: __EventObj__<T[K]> & {
    (handle: __WebviewWindow__): __EventObj__<T[K]>;
  };
};

export function makeLiveEvent<T extends Record<string, any>>(ev: EventsShape<T>) {
  return function liveEvent<K extends keyof T>(key: K) {
    return (handler: (payload: T[K]) => void) => {
      const obj = ev[key] as __EventObj__<T[K]>;
      return obj.listen((e) => handler(e.payload));
    };
  };
}

// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE, Channel } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	exists: (path: string) => typedError<boolean, string>(__TAURI_INVOKE("exists", { path })),
	appReady: () => __TAURI_INVOKE<void>("app_ready"),
	getMouseAndWindowPosition: () => typedError<MouseWindowInfo, string>(__TAURI_INVOKE("get_mouse_and_window_position")),
	getWindowKind: () => __TAURI_INVOKE<WindowKindInfo>("get_window_kind"),
	prewarmWindow: (name: WindowName) => __TAURI_INVOKE<void>("prewarm_window", { name }),
	discardPrewarmWindow: (name: WindowName) => __TAURI_INVOKE<boolean>("discard_prewarm_window", { name }),
	recordRendererBootstrapReady: () => __TAURI_INVOKE<void>("record_renderer_bootstrap_ready"),
	createWindow: (name: WindowName, options: {
	width: number | null,
	height: number | null,
} | null) => __TAURI_INVOKE<void>("create_window", { name, options }),
	greet: (name: string) => typedError<string, string>(__TAURI_INVOKE("greet", { name })),
	clean: () => typedError<string, string>(__TAURI_INVOKE("clean")),
	templateBootstrap: () => typedError<TemplateDashboard, string>(__TAURI_INVOKE("template_bootstrap")),
	templateSnapshot: () => typedError<TemplateDashboard, string>(__TAURI_INVOKE("template_snapshot")),
	templateCreateMember: (input: NewMemberInput) => typedError<TemplateDashboard, string>(__TAURI_INVOKE("template_create_member", { input })),
	templateCreateTask: (input: NewTaskInput) => typedError<TemplateDashboard, string>(__TAURI_INVOKE("template_create_task", { input })),
	templateAssignTask: (input: AssignTaskInput) => typedError<TemplateDashboard, string>(__TAURI_INVOKE("template_assign_task", { input })),
	templateUnassignTask: (input: UnassignTaskInput) => typedError<TemplateDashboard, string>(__TAURI_INVOKE("template_unassign_task", { input })),
	templateBulkSetStatus: (input: BulkStatusInput) => typedError<TemplateDashboard, string>(__TAURI_INVOKE("template_bulk_set_status", { input })),
	templateReset: () => typedError<TemplateDashboard, string>(__TAURI_INVOKE("template_reset")),
};

/** Events */
export const events = {
	//@type {ReturnType<typeof makeEvent<FullScreenEvent>>}
	fullScreenEvent: makeEvent<FullScreenEvent>("full-screen-event"),
};

/* Types */export type AssignTaskInput = {
	task_id: string,
	member_id: string,
};

export type BulkStatusInput = {
	task_ids: string[],
	status: string,
};

export type CreateWindowOptions = {
	width: number | null,
	height: number | null,
};

export type DemoStats = {
	total_members: number,
	total_tasks: number,
	todo_tasks: number,
	doing_tasks: number,
	done_tasks: number,
};

export type FullScreenEvent = {
	is_fullscreen: boolean,
};

// Application-facing id type that accepts either string or integer ids.
export type Id = 
// String record key.
{ String: string } | 
// Integer record key.
{ Number: number };

export type Member = {
	id: Id,
	name: string,
	role: string,
	created_at: number,
};

export type MouseWindowInfo = {
	mouse_x: number,
	mouse_y: number,
	window_x: number,
	window_y: number,
	window_width: number,
	window_height: number,
	rel_x: number,
	rel_y: number,
	pixel_ratio: number,
};

export type NewMemberInput = {
	id: string,
	name: string,
	role: string,
};

export type NewTaskInput = {
	id: string,
	title: string,
	notes: string,
	status: string,
	priority: number,
};

export type Task = {
	id: Id,
	title: string,
	notes: string,
	status: string,
	priority: number,
	owner_id: string | null,
	created_at: number,
	updated_at: number,
};

export type TaskAssignmentView = {
	task_id: string,
	member_id: string,
};

export type TemplateDashboard = {
	members: Member[],
	tasks: Task[],
	assignments: TaskAssignmentView[],
	stats: DemoStats,
};

export type UnassignTaskInput = {
	task_id: string,
};

export type WindowKindInfo = {
	window: WindowName | null,
	label: string,
	is_primary_main: boolean,
	is_user_window: boolean,
	is_prepared_window: boolean,
};

export type WindowName = "Main";

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

function makeEvent<T>(name: string) {
    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, cb),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, cb),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, payload) as unknown) as (T extends null ? () => Promise<void> : (payload: T) => Promise<void>)
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, cb),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, cb),
        emit: ((payload: T) => target.emit(name, payload) as unknown) as (T extends null ? () => Promise<void> : (payload: T) => Promise<void>)
    });

    return Object.assign(fn, base);
}
