/* eslint-disable */

export type EventsShape<T extends Record<string, any>> = {
  [K in keyof T]: __EventObj__<T[K]> & {
    (handle: __WebviewWindow__): __EventObj__<T[K]>;
  };
};

export function makeLievt<T extends Record<string, any>>(ev: EventsShape<T>) {
  return function lievt<K extends keyof T>(key: K) {
    return (handler: (payload: T[K]) => void) => {
      const obj = ev[key] as __EventObj__<T[K]>;
      return obj.listen((e) => handler(e.payload));
    };
  };
}

// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async exists(path: string) : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("exists", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async appReady() : Promise<void> {
    await TAURI_INVOKE("app_ready");
},
async getMouseAndWindowPosition() : Promise<Result<MouseWindowInfo, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_mouse_and_window_position") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getWindowKind() : Promise<WindowKindInfo> {
    return await TAURI_INVOKE("get_window_kind");
},
async createWindow(name: WindowName, options: CreateWindowOptions | null) : Promise<void> {
    await TAURI_INVOKE("create_window", { name, options });
},
async greet(name: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("greet", { name }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async clean() : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("clean") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async templateBootstrap() : Promise<Result<TemplateDashboard, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("template_bootstrap") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async templateSnapshot() : Promise<Result<TemplateDashboard, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("template_snapshot") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async templateCreateMember(input: NewMemberInput) : Promise<Result<TemplateDashboard, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("template_create_member", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async templateCreateTask(input: NewTaskInput) : Promise<Result<TemplateDashboard, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("template_create_task", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async templateAssignTask(input: AssignTaskInput) : Promise<Result<TemplateDashboard, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("template_assign_task", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async templateUnassignTask(input: UnassignTaskInput) : Promise<Result<TemplateDashboard, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("template_unassign_task", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async templateBulkSetStatus(input: BulkStatusInput) : Promise<Result<TemplateDashboard, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("template_bulk_set_status", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async templateReset() : Promise<Result<TemplateDashboard, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("template_reset") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/


export const events = __makeEvents__<{
fullScreenEvent: FullScreenEvent
}>({
fullScreenEvent: "full-screen-event"
})

/** user-defined constants **/



/** user-defined types **/

export type AssignTaskInput = { task_id: string; member_id: string }
export type BulkStatusInput = { task_ids: string[]; status: string }
export type CreateWindowOptions = { width: number | null; height: number | null }
export type DemoStats = { total_members: number; total_tasks: number; todo_tasks: number; doing_tasks: number; done_tasks: number }
export type FullScreenEvent = { is_fullscreen: boolean }
export type Id = string | number
export type Member = { id: Id; name: string; role: string; created_at: number }
export type MouseWindowInfo = { mouse_x: number; mouse_y: number; window_x: number; window_y: number; window_width: number; window_height: number; rel_x: number; rel_y: number; pixel_ratio: number }
export type NewMemberInput = { id: string; name: string; role: string }
export type NewTaskInput = { id: string; title: string; notes: string; status: string; priority: number }
export type Task = { id: Id; title: string; notes: string; status: string; priority: number; owner_id: string | null; created_at: number; updated_at: number }
export type TaskAssignmentView = { task_id: string; member_id: string }
export type TemplateDashboard = { members: Member[]; tasks: Task[]; assignments: TaskAssignmentView[]; stats: DemoStats }
export type UnassignTaskInput = { task_id: string }
export type WindowKindInfo = { window: WindowName | null; is_prewarm: boolean; label: string; is_primary_main: boolean }
export type WindowName = "Main"

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
